# This is a basic workflow to help you get started with Actions

name: BuildDeb

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Build in arm64
        # You may pin to the exact commit or the version.
        # uses: uraimo/run-on-arch-action@07a46afceb4aea01aaa545fedfff61ad9e4c7df0
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          # CPU architecture: armv6, armv7, aarch64, s390x, ppc64le.
          arch: aarch64
          # Linux distribution name: ubuntu16.04, ubuntu18.04, ubuntu20.04, bullseye, buster, stretch, jessie, fedora_latest, alpine_latest, archarm_latest.
          distro: ubuntu20.04
          # Your GitHub token, used for caching Docker images in your project's public package registry. Usually this would just be $\{{ github.token }}. This speeds up builds and is highly recommended.
          githubToken: ${{ github.token }}
          env: |
            BRANCH: "Percona-Server-5.7.34-37"
            GIT_REPO: "https://github.com/percona/percona-server.git"
            RPM_RELEASE: "1"
            DEB_RELEASE: "1"
          # Shell commands to execute in the container.
          run: |
            echo "Starting build perconna-server"
            set -o xtrace
            apt-get update && apt-get install -y wget
            rm -rf test || true
            mkdir test
            wget https://raw.githubusercontent.com/percona/percona-server/${BRANCH}/build-ps/percona-server-5.7_builder.sh -O percona-server_builder.sh
            sed -i 's:sudo::g' percona-server_builder.sh
            export build_dir=$(pwd -P)
            set -o xtrace
            cd ${build_dir}
            bash -x ./percona-server_builder.sh --builddir=${build_dir}/test --install_deps=1
            bash -x ./percona-server_builder.sh --builddir=${build_dir}/test --repo=${GIT_REPO} --branch=${BRANCH} --rpm_release=${RPM_RELEASE} --deb_release=${DEB_RELEASE} --build_deb=1
