# This is a basic workflow to help you get started with Actions

name: BuildDeb

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      MAJOR_VERSION: "5.7"
      VERSION: "5.7.34-37"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download deb source
        run: |
          apt-get update && apt-get install -y wget
          mkdir -p artifacts/source_deb
          cd artifacts/source_deb
          wget https://downloads.percona.com/downloads/Percona-Server-${MAJOR_VERSION}/Percona-Server-${VERSION}/source/debian/percona-server-${MAJOR_VERSION}_${VERSION}-1.debian.tar.gz
          wget https://downloads.percona.com/downloads/Percona-Server-${MAJOR_VERSION}/Percona-Server-${VERSION}/source/debian/percona-server-${MAJOR_VERSION}_${VERSION}-1.dsc
          wget https://downloads.percona.com/downloads/Percona-Server-${MAJOR_VERSION}/Percona-Server-${VERSION}/source/debian/percona-server-${MAJOR_VERSION}_${VERSION}-1_source.changes
          wget https://downloads.percona.com/downloads/Percona-Server-${MAJOR_VERSION}/Percona-Server-${VERSION}/source/debian/percona-server-${MAJOR_VERSION}_${VERSION}.orig.tar.gz
          
      - name: Build in arm64
        # You may pin to the exact commit or the version.
        # uses: uraimo/run-on-arch-action@07a46afceb4aea01aaa545fedfff61ad9e4c7df0
        uses: uraimo/run-on-arch-action@v2.1.1
        continue-on-error: true
        id: build-arm64
        with:
          # CPU architecture: armv6, armv7, aarch64, s390x, ppc64le.
          arch: aarch64
          # Linux distribution name: ubuntu16.04, ubuntu18.04, ubuntu20.04, bullseye, buster, stretch, jessie, fedora_latest, alpine_latest, archarm_latest.
          distro: ubuntu20.04
          # Your GitHub token, used for caching Docker images in your project's public package registry. Usually this would just be $\{{ github.token }}. This speeds up builds and is highly recommended.
          githubToken: ${{ github.token }}
          env: |
            BRANCH: "Percona-Server-${{ env.VERSION }}"
            GIT_REPO: "https://github.com/percona/percona-server.git"
            RPM_RELEASE: "1"
            DEB_RELEASE: "1"
          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          install: |
            export DEBIAN_FRONTEND="noninteractive"
            apt-get update && apt-get install -y wget dpkg-dev devscripts
            apt-get install -y bison cmake debhelper libaio-dev libmecab-dev libncurses5-dev po-debconf psmisc zlib1g-dev libreadline-dev libpam-dev libssl-dev libnuma-dev libwrap0-dev dh-systemd libcurl4-openssl-dev
          # Shell commands to execute in the container.
          run: |
            set -o xtrace
            set -eu
            echo "Starting build perconna-server"
            rm -rf test || true
            mkdir test
            cp -r /artifacts/source_deb test/
            wget https://raw.githubusercontent.com/percona/percona-server/${BRANCH}/build-ps/percona-server-5.7_builder.sh -O percona-server_builder.sh
            sed -i 's:sudo::g' percona-server_builder.sh
            sed -i 's/percona-release enable tools testing/#percona-release enable tools testing/g' percona-server_builder.sh
            export build_dir=$(pwd -P)
            cd ${build_dir}
            export DEBIAN_FRONTEND="noninteractive"
            apt-get -y install dirmngr || true
            apt-get -y install lsb-release wget
            apt-get -y purge eatmydata || true
            apt-get -y install psmisc pkg-config libsasl2-modules libsasl2-modules-ldap libsasl2-dev
            apt-get -y install dh-systemd curl bison cmake perl libssl-dev gcc g++ libaio-dev libldap2-dev libwrap0-dev gdb unzip gawk
            apt-get -y install lsb-release libmecab-dev libncurses5-dev libreadline-dev libpam-dev zlib1g-dev
            apt-get -y install libldap2-dev libnuma-dev libjemalloc-dev libeatmydata libc6-dbg valgrind libjson-perl python-mysqldb libsasl2-dev
            apt-get -y install libmecab2 mecab mecab-ipadic
            apt-get -y install build-essential devscripts libnuma-dev
            apt-get -y install cmake autotools-dev autoconf automake build-essential devscripts debconf debhelper fakeroot 
            apt-get -y install libcurl4-openssl-dev patchelf
            export DIST="$(lsb_release -sc)"
            if [ "x${DIST}" = "xcosmic" -o "x${DIST}" = "xbionic" -o "x${DIST}" = "xdisco" -o "x${DIST}" = "xbuster" -o "x${DIST}" = "xfocal" ]; then
                apt-get -y install libeatmydata1
            fi
            bash -x ./percona-server_builder.sh --builddir=${build_dir}/test --repo=${GIT_REPO} --branch=${BRANCH} --rpm_release=${RPM_RELEASE} --deb_release=${DEB_RELEASE} --build_deb=1
            cp -r deb /artifacts/
      
      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"
      
      - name: release
        uses: ncipollo/release-action@v1
        with:
          tag: "Percona-Server-${{ env.VERSION }}"
          artifacts: "artifacts/deb/*"
          token: ${{ secrets.GITHUB_TOKEN }}
